---
- name: add test
  ansibleguy.opnsense.rule:
    source_net: '192.168.0.0/24'
    destination_net: '192.168.10.0/24'
    destination_port: 443
    protocol: 'TCP'
    description: 'Test rule'
    match_fields: ['description']
    state: absent
