---
- name: setup syslog target
  ansibleguy.opnsense.syslog:
    description: 'Test{{ syslog_desc_postfix }}'
    enabled: true
    target: 10.10.1.10
    port: 9000
    transport: tcp4
    rfc5424: true
    match_fields:
    - description
    program:
    - filterlog
    - suricata
