---
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: kuard
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard-1
    ports:
    - containerPort: 8080
      hostPort: 8080
