{
 "title": "OPNsense",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Unbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Domain",
     "type": "piechart",
     "gridPos": { "h": 18, "w": 9, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by(domain) (count_over_time({job=\"syslog\"} | unpack |= `reply` [$__range])))"
      }
     ]
    },
    {
     "title": "Source",
     "type": "piechart",
     "gridPos": { "h": 18, "w": 9, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by(srcip) (count_over_time({job=\"syslog\"} | unpack |= \"reply\" [$__range])))"
      }
     ]
    }
   ]
  },
  { "title": "Pi-hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Firewall",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(block_domain) (count_over_time({source=\"vector\"} | json | host=\"pihole1\" | appname=\"pihole\" [$__range])))"
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | host=\"pihole1\" | appname=\"pihole\""
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "IP Address",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | host=\"OPNsense.localdomain\" | appname=\"filterlog\""
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | host=\"OPNsense.localdomain\" | appname=\"filterlog\""
    }
   ]
  },
  {
   "title": "Internet Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(internet_speed_download)", "legendFormat": "Down" },
    { "expr": "sum(internet_speed_upload)", "legendFormat": "Up" }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "mem_used_percent", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_used_percent{path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "100 - cpu_usage_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_n_users", "legendFormat": "__auto" }
   ]
  }
 ]
}