# https://grafana.com/docs/loki/latest/configuration/examples/#1-local-configuration-exampleyaml
# https://github.com/grafana/loki/issues/5123

auth_enabled: false

server:
  http_listen_port: 3100 # default
  grpc_listen_port: 9095 # default

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

frontend:
  max_outstanding_per_tenant: 10000

common:
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules

  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2023-01-01
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/boltdb-cache
