{
 "title": "pve1",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "pve1, pihole1, monitoring1" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Access",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | host = `opnsense1` | appname = `filterlog`"
    }
   ]
  },
  {
   "title": "Pi-hole Top Blocked",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(20, sum by(block_domain) (count_over_time({source=\"vector\"} | json | host=\"pihole1\" | appname=\"pihole\" [$__range])))"
    }
   ]
  },
  {
   "title": "Pi-hole Block Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | appname = `pihole`"
    }
   ]
  },
  {
   "title": "Suricata Top Signature",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(20, sum by(message_alert_signature) (count_over_time({source=\"vector\"} | json | host = `opnsense1` | appname = `suricata` [$__range])))"
    }
   ]
  },
  {
   "title": "Suricata Top Category",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(20, sum by(message_alert_category) (count_over_time({source=\"vector\"} | json | host = `opnsense1` | appname = `suricata` [$__range])))"
    }
   ]
  },
  {
   "title": "Suricata Top Signature",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(20, sum by(message_alert_signature) (count_over_time({source=\"vector\"} | json | host = `opnsense1` | appname = `suricata` [$__range])))"
    }
   ]
  },
  {
   "title": "Suricata Top Category",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "topk(20, sum by(message_alert_category) (count_over_time({source=\"vector\"} | json | host = `opnsense1` | appname = `suricata` [$__range])))"
    }
   ]
  },
  {
   "title": "Suricata Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{source=\"vector\"} | json | host = `opnsense1` | appname = `suricata`"
    }
   ]
  },
  { "title": "System Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (host) (rate(node_cpu_seconds_total{mode=\"idle\",host=\"opnsense1\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by (host) (rate(host_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{host=\"opnsense1\"}",
     "legendFormat": "{{host}}"
    },
    { "expr": "host_memory_available_bytes", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "Host: opnsense1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "opnsense1: CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (host) (rate(node_cpu_seconds_total{mode=\"idle\",host=\"opnsense1\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opnsense1: Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{host=\"opnsense1\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "opnsense1: Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{host=\"opnsense1\"}[$__interval]) * 8",
     "legendFormat": "{{host}} recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{host=\"opnsense1\"}[$__interval]) * 8",
     "legendFormat": "{{host}} trans {{device}}"
    }
   ]
  },
  {
   "title": "opnsense1: Free Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{host=\"opnsense1\", device=\"zroot\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Host: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "host" },
  {
   "title": "$host: CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (host) (rate(host_cpu_seconds_total{mode=\"idle\",host=\"$host\"}[1m])) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$host: Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "host_memory_available_bytes{host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$host: Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(host_network_receive_bytes_total{host=\"$host\"}[$__interval]) * 8",
     "legendFormat": "{{host}} recv {{device}}"
    },
    {
     "expr": "irate(host_network_transmit_bytes_total{host=\"$host\"}[$__interval]) * 8",
     "legendFormat": "{{host}} trans {{device}}"
    }
   ]
  },
  {
   "title": "$host: Free Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "host_filesystem_free_bytes{host=\"$host\", mountpoint=\"/\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}