---
- name: check podman install
  ansible.builtin.command: which podman
  ignore_errors: true
  register: podman_install

- name: install podman
  when: podman_install.rc != 0
  block:
  - name: install podman
    ansible.builtin.apt:
      name: podman
      update_cache: yes
      state: latest

  - name: copy podman config
    ansible.builtin.copy:
      src: ../files/containers-storage.conf
      dest: /etc/containers/storage.conf
      mode: '0644'

  - name: reset podman
    ansible.builtin.command: podman system reset -f

- name: run hello-world
  containers.podman.podman_container:
    name: hello-world
    image: docker.io/library/hello-world:latest
    state: started
    rm: true
