[sources.firewall]
type = "syslog"
address = "0.0.0.0:9000"
mode = "udp"

[transforms.firewall_filterlog]
type = "remap"
inputs = ["firewall"]
source = '''
  if .appname == "filterlog" {
    message_array = parse_csv!(string!(.message))
    # ipv4 and ipv6
    if message_array[8] == "4" || message_array[8] == "6" {
      .filteriface   = message_array[4]
      .filterflow    = message_array[7]
      .filteraction  = message_array[6]
      .filteripver   = message_array[8]
      # ipv4
      if message_array[8] == "4" {
        .filterproto   = message_array[16]
        .filterflags   = message_array[23]
        .filtersrcip   = message_array[18]
        .filtersrcport = message_array[20]
        .filterdstip   = message_array[19]
        .filterdstport = message_array[21]
      # ipv6
      } else if message_array[8] == "6" {
        .filterproto   = message_array[12]
        #.filterflags   = "IPv6 not fully supported"
        .filtersrcip   = message_array[15]
        .filtersrcport = message_array[17]
        .filterdstip   = message_array[16]
        .filterdstport = message_array[18]
      }
    }
  }
'''

[transforms.firewall_split]
type = "route"
inputs = ["firewall_filterlog"]
route.pass = '.filteraction == "pass"'
route.therest = '.filteraction != "pass"'

[transforms.firewall_geotag]
type = "geoip"
inputs = ["firewall_split.pass"]
database = "/etc/vector/GeoLite2-City.mmdb"
source = "filtersrcip"
target = "geotag"

[sinks.loki_firewall]
type = "loki"
inputs = ["firewall_split.therest", "firewall_geotag"]
encoding.codec = "json"
endpoint = "http://0.0.0.0:3100"
labels.logtype = "net"
labels.server = "firewall"
