# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: grafana
  name: grafana
spec:
  containers:
  - image: docker.io/grafana/grafana-oss:latest
    name: grafana-1
    ports:
    - containerPort: 3000
      hostPort: 3000
