# - name: check opnsense items
#   ansibleguy.opnsense.list:
#     target: 'syslog'
#     debug: true
#   register: syslog
#
# - ansible.builtin.debug:
#     var: syslog
#
# - name: setup syslog target - vector
#   ansibleguy.opnsense.syslog:
#     description: 'Vector'
#     enabled: true
#     target: '10.10.1.5'
#     port: 9000
#     transport: 'tcp4'
#     rfc5424: true
#     program:
#     - filterlog

- name: setup syslog target - promtail
  ansibleguy.opnsense.syslog:
    description: 'Promtail{{ syslog_desc_postfix }}'
    enabled: false
    target: '10.10.1.5'
    port: 1514
    transport: 'tcp4'
    rfc5424: true
    match_fields:
    - description
    program:
    - filterlog
    - unbound
