- name: start suricata
  ansibleguy.opnsense.service:
    name: ids
    action: start

- name: start syslog
  ansibleguy.opnsense.service:
    name: syslog
    action: start

- name: start telegraf
  ansibleguy.opnsense.service:
    name: telegraf
    action: start
