---
api_host: 'pve1'
api_user: 'root@pam'
api_password: 'password'
api_token_id: ansible
api_token_secret: 4faf5ce0-f774-436e-8ddb-6e48dceb3899

defaults:
  node: 'pve1'
  onboot: true
  pubkey: '{{ lookup("file", "~/.ssh/mangkoran-8atagor_ed25519.pub")}}'
  cores: '1'
  cpu: '1'
  memory: '1024'
  storage: 'local-zfs'
  disk: 'local-zfs:4'
  nameserver: '1.1.1.1'
  ostemplate: 'local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst'

containers:
  # pihole1:
  #   vmid: '200'
  #   node: 'pve1'
  #   onboot: true
  #   password: 'password'
  #   cores: '1'
  #   memory: '512'
  #   swap: '0'
  #   storage: 'local-zfs'
  #   disk: 'local-zfs:4'
  #   features:
  #   - fuse=1
  #   - keyctl=1
  #   - nesting=1
  #   netif:
  #     net0: 'name=eth0,bridge=vmbr0,ip=10.10.1.7/24,gw=10.10.1.1'
  #
  # monitoring1:
  #   vmid: '201'
  #   node: 'pve1'
  #   onboot: true
  #   password: 'password'
  #   cores: '1'
  #   memory: '1024'
  #   swap: '0'
  #   storage: 'local-zfs'
  #   disk: 'local-zfs:8'
  #   features:
  #   - fuse=1
  #   - keyctl=1
  #   - nesting=1
  #   netif:
  #     net0: 'name=eth0,bridge=vmbr0,ip=10.10.1.6/24,gw=10.10.1.1'

  test1:
    vmid: '300'
    node: 'pve1'
    onboot: true
    password: 'password'
    cores: '1'
    memory: '512'
    swap: '0'
    storage: 'local-zfs'
    disk: 'local-zfs:8'
    features:
    - fuse=1
    - keyctl=1
    - nesting=1
    netif:
      net0: 'name=eth0,bridge=vmbr0,ip=10.10.1.30/24,gw=10.10.1.1'
