# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  annotations:
  labels:
    app: pihole
spec:
  replicas: 1 # podman cant use >1 replicas
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      annotations:
      labels:
        app: pihole
    spec:
      hostNetwork: true # https://github.com/containers/podman/issues/19108#issuecomment-1619920541
      containers:
      - name: pihole
        image: docker.io/pihole/pihole:latest
        env:
        - name: TZ
          value: Asia/Kuala_Lumpur
        - name: DNSMASQ_LISTENING
          value: all
        - name: WEBPASSWORD
          value: password
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        volumeMounts:
        - name: pihole
          mountPath: /etc/pihole:Z
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d:Z
        - name: log-pihole
          mountPath: /var/log/pihole
      - name: vector
        image: docker.io/timberio/vector:latest-alpine
        args:
        - --config=/etc/vector/vector.yml
        env:
        - name: PROCFS_ROOT
          value: /hostfs/proc
        - name: SYSFS_ROOT
          value: /hostfs/sys
        ports:
        - containerPort: 9598
          hostPort: 9598
          protocol: TCP
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector/vector.yml:ro
        - name: log-pihole
          mountPath: /var/log/pihole:ro
        - name: host-proc-fs
          mountPath: /hostfs/proc
        - name: host-sys-fs
          mountPath: /hostfs/sys
      volumes:
      - name: pihole
        hostPath:
          path: /root/podman/pihole/etc-pihole
          type: Directory
      - name: dnsmasq
        hostPath:
          path: /root/podman/pihole/etc-dnsmasq.d
          type: Directory
      - name: vector-config
        hostPath:
          path: /root/podman/vector/vector-config.yml
          type: File
      - name: log-pihole
        hostPath:
          path: /root/podman/pihole/log-pihole
          type: Directory
      - name: host-proc-fs
        hostPath:
          path: /proc
          type: Directory
      - name: host-sys-fs
        hostPath:
          path: /sys
          type: Directory
