---
- name: make pihole deployment volume directory
  ansible.builtin.file:
    path: '/root/podman/{{ item.path }}'
    state: directory
  loop:
  - { path: pihole/etc-dnsmasq.d }
  - { path: pihole/etc-pihole }
  - { path: pihole/log-pihole }
  - { path: vector }

- name: update component config and deployment manifest
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
  - src: ../files/vector-pihole.yml
    dest: /root/podman/vector/vector-config.yml
  - src: ../files/pihole-deployment.yml
    dest: /root/podman/pihole-deployment.yml

- name: create pihole deployment
  containers.podman.podman_play:
    kube_file: /root/podman/pihole-deployment.yml
    network: bridge # github.com/containers/podman/issues/19108
    state: started
