---
- name: install podman
  register: podman_install
  ansible.builtin.apt:
    name: podman
    update_cache: yes
    state: present

- name: update podman config
  when: podman_install.changed == true
  block:
  - name: update podman config
    ansible.builtin.copy:
      src: ../files/containers-storage.conf
      dest: /etc/containers/storage.conf
      mode: '0644'

  - name: reset podman
    ansible.builtin.command: podman system reset -f

- name: run hello-world
  containers.podman.podman_container:
    name: hello_world
    image: docker.io/library/hello-world:latest
    state: started
    rm: true
